name: "init terraform"
description: "terraform init & credentials"


inputs:
  ACCESS_KEY:
    required: true
    description: "aws access key"
  SECRET_ACCESS_KEY:
    required: true
    description: "aws secret access key"
  ENVIRONMENT:
    required: true
    description: "env"
  WORKING_DIRECTORY:
    required: true
    description: "iac"



runs:
  using: "composite"
  steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: change directory
      run: |
        cd ${{inputs.WORKING_DIRECTORY}}
      shell: bash

    - name: configure terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.4.5

    - name: configure credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.ACCESS_KEY }}
        aws-secret-access-key: ${{ inputs.SECRET_ACCESS_KEY }}
        aws-region: eu-west-3

    - name: init terraform
      run: terraform init -backend-config=./var/${{ inputs.ENVIRONMENT }}/backend.tfbackend -reconfigure
      shell: bash