name: 'MANUAL DEPLOYMENT'
run-name: 'Manual deployment on environment ${{ inputs.environment }} from branch ${{github.ref_name}} execute by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        default: test
        options:
          - test
          - prod

env:
  NODE_VERSION: 20

jobs:

  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "setup-node"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Manage cache"
        uses: ./.github/actions/manage-cache/
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          LOCK_PATH: "**/package-lock.json"

      - name: "Install dependencies"
        run: |
          npm ci
          npm run build
          zip lambda/build/index.zip lambda/build/index.js
        shell: bash

  plan:
    needs:
      - setup-environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac/
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: "Terraform init"
        uses: ./.github/actions/init-terraform/
        with:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          WORKING_DIRECTORY: ./iac/

      - name: "Manage cache"
        uses: ./.github/actions/manage-cache/
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          LOCK_PATH: "**/package-lock.json"

      - name: plan terraform
        run: |
          output=$(terraform plan -var-file="./var/${{ github.event.inputs.environment }}/values.tfvars" -no-color)
          echo "## Terraform Plan Output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "$output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        shell: bash
  
  deploy:
    needs:
      - plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac/
    environment:
      name: ${{ github.event.inputs.environment }}
      url: "https://cv-demo-${{ github.event.inputs.environment }}.theo-tonneau.com"
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: "Terraform init"
        uses: ./.github/actions/init-terraform/
        with:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          WORKING_DIRECTORY: ./iac/

      - name: "Manage cache"
        uses: ./.github/actions/manage-cache/
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          LOCK_PATH: "**/package-lock.json"

      - name: apply terraform
        run: terraform apply -var-file="./var/${{ github.event.inputs.environment }}/values.tfvars" -auto-approve
        shell: bash