name: 'SYNC-S3'
run-name: 'Sync-S3 on environment ${{ inputs.environment }} from branch ${{github.ref_name}} execute by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        default: test
        options:
          - test
          - prod

env:
  NODE_VERSION: 20

jobs:

  sync-s3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac/
    environment:
      name: ${{ github.event.inputs.environment }}
      url: "https://cv-demo-${{ github.event.inputs.environment }}.theo-tonneau.com"
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: configure terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.5

      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - run: |
          npm ci
          mkdir -p ../src/js/
        shell: bash

      - name: init terraform
        run: terraform init -backend-config=./var/${{ github.event.inputs.environment }}/backend.tfbackend -reconfigure
        shell: bash

      - name: "Terraform output"
        run: |
          mkdir -p ../src/js/
          touch ../src/js/config.json
          terraform output -json > ../src/js/config.json
        shell: bash

      - name: "Get informations files"
        run: |
          echo "${{ secrets.ENCRYPT }}" > ../src/ts/encrypt.ts
        shell: bash

      - name: "Compile and build webpage"
        run: |
          npm install
          npm run build-app
        shell: bash

      - name: sync-s3
        run: |
          aws s3 cp ../src/ s3://cv-demo-tonneau-test/ --recursive \
          --exclude "*" \
          --include "index.html" \
          --include "fr/index.html" \
          --include "fr/module/*" \
          --include "en/index.html" \
          --include "en/module/*" \
          --include "img/*" \
          --include "img/certification/*" \
          --include "img/company/*" \
          --include "img/website/*" \
          --include "js/index.js" \
          --include "js/cookie.js" \
          --include "css/*" \
          --exclude "ts/*"
        shell: bash

      - name: "Invalid cache cloudfront"
        uses: ./.github/actions/invalid-cache/
        with:
          BUCKET_NAME: cv-demo-tonneau-${{ github.event.inputs.environment }}
