name    : CONTINUOUS INTEGRATION
run-name: 'CONTINUOUS INTEGRATION'

env:
  environment: 'test'

defaults: 
  run: 
    shell: bash

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: build lambda
        run: |
          npm ci
          npm run build

      - name: "Run terraform fmt check actions"
        uses: ./.github/actions/terraform-check
        id: check-terraform
        with:
          GH_TOKEN: ${{ secrets.PERSONNAL_ACCESS_TOKEN }}
          WORKING_DIR: ./iac/

      - name: create step summary 
        if: always()
        run: |
          {
            echo "### :rocket: Workflow status"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Check Terraform            |  ${{ steps.check-terraform.outcome }} |"
          } >> $GITHUB_STEP_SUMMARY
